version: 2
updates:
  - package-ecosystem: 'npm'
    allow:
      - dependency-type: 'production'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
